// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBygjM7lsk0Y7DuMAvzpmug7KutbfjR3CE',
    appId: '1:463563858018:web:f64083eeadb5d60093b13b',
    messagingSenderId: '463563858018',
    projectId: 'com-example-kg',
    authDomain: 'com-example-kg.firebaseapp.com',
    storageBucket: 'com-example-kg.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALf01PoiyUj_sVux97XYaYncVX6QsCoII',
    appId: '1:463563858018:android:297299d6ec5718df93b13b',
    messagingSenderId: '463563858018',
    projectId: 'com-example-kg',
    storageBucket: 'com-example-kg.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB07ZYXWHaV6oDrHc8VX96stkWZHVn-Org',
    appId: '1:463563858018:ios:29d95dd25a7f6c2093b13b',
    messagingSenderId: '463563858018',
    projectId: 'com-example-kg',
    storageBucket: 'com-example-kg.firebasestorage.app',
    iosBundleId: 'com.example.kg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB07ZYXWHaV6oDrHc8VX96stkWZHVn-Org',
    appId: '1:463563858018:ios:29d95dd25a7f6c2093b13b',
    messagingSenderId: '463563858018',
    projectId: 'com-example-kg',
    storageBucket: 'com-example-kg.firebasestorage.app',
    iosBundleId: 'com.example.kg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBygjM7lsk0Y7DuMAvzpmug7KutbfjR3CE',
    appId: '1:463563858018:web:780afdb79bca62e293b13b',
    messagingSenderId: '463563858018',
    projectId: 'com-example-kg',
    authDomain: 'com-example-kg.firebaseapp.com',
    storageBucket: 'com-example-kg.firebasestorage.app',
  );

}